ibexa_fieldtype_richtext:
    custom_tags:
        accordion:
            template: '@standard/ibexa_richtext/custom_tags/accordion.html.twig'
            icon: '/bundles/ibexaicons/img/all-icons.svg#menu'
            attributes:
                title:
                    type: string
                    required: false

ibexa:
    system:
        admin_group:
            fieldtypes:
                ibexa_richtext:
                    custom_tags:
                        - accordion
                    toolbar:
                        custom_tags_group:
                            buttons:
                                accordion:
                                    priority: 92