ibexa_fieldtype_richtext:
    custom_tags:
        panel:
            template: '@standard/ibexa_richtext/custom_tags/panel.html.twig'
            icon: "/bundles/ibexaicons/img/all-icons.svg#wand"
            attributes:
                title:
                    type: string
                    required: false
                style:
                    type: string
                    required: false
                icon:
                    type: string
                    required: false

ibexa:
    system:
        admin_group:
            fieldtypes:
                ibexa_richtext:
                    custom_tags:
                        - panel
                    toolbar:
                        custom_tags_group:
                            buttons:
                                panel:
                                    priority: 91