ibexa_fieldtype_richtext:
    custom_tags:
        rawhtml:
            template: "@ibexadesign/ezrichtext/custom_tags/rawhtml.html.twig"
            icon: '/bundles/ibexaicons/img/all-icons.svg#information'
            attributes:
                name:
                    type: string

# https://github.com/ezsystems/ezplatform-rawhtml-richtext-tag/tree/master/Resources/config
ibexa:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    custom_tags:
                        - rawhtml
                    toolbar:
                        custom_tags_group:
                            buttons:
                                rawhtml:
                                    priority: 95