ibexa_fieldtype_richtext:
    custom_tags:
        vimeo:
            template: '@standard/ibexa_richtext/custom_tags/vimeo.html.twig'
#            icon: "/bundles/ibexaicons/img/all-icons.svg#video"
            icon: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#video'
            attributes:
                title:
                    type: string
                    required: false
                url:
                    type: string
                    required: false

ibexa:
    system:
        admin_group:
            fieldtypes:
                ibexa_richtext:
                    custom_tags:
                        - vimeo
                    toolbar:
                        custom_tags_group:
                            buttons:
                                vimeo:
                                    priority: 93