## see vendor/ibexa/core/src/bundle/Core/Resources/config/storage/legacy/schema.yaml

# ?? comment
# ?? credits
drop table ez_ct_change_entry;
drop table ez_ct_change_log;
drop table ezapprove_items;
drop table ezbasket;
# keep ezbinaryfile
# keep ezcobj_state
# keep ezcobj_state_group
# keep ezcobj_state_group_language
# keep ezcobj_state_language
# keep ezcobj_state_link
drop table ezcollab_group;
drop table ezcollab_item;
drop table ezcollab_item_group_link;
drop table ezcollab_item_message_link;
drop table ezcollab_item_participant_link;
drop table ezcollab_item_status;
drop table ezcollab_notification_rule;
drop table ezcollab_profile;
drop table ezcollab_simple_message;
drop table ezcomment;
drop table ezcomment_notification;
drop table ezcomment_subscriber;
drop table ezcomment_subscription;
# new ezcontent_language
# new ezcontentbrowsebookmark
# new ezcontentbrowserecent
# new ezcontentclass
# new ezcontentclass_attribute
# new ezcontentclass_attribute_ml
# new ezcontentclass_classgroup
# new ezcontentclass_name
# new ezcontentclassgroup
# new ezcontentobject
# new ezcontentobject_attribute
# new ezcontentobject_link
# new ezcontentobject_name
# new ezcontentobject_trash
# new ezcontentobject_tree
# new ezcontentobject_version
drop table ezcurrencydata;
# new ezdatebasedpublisher_scheduled_entries
drop table ezdiscountrule;
drop table ezdiscountsubrule;
drop table ezdiscountsubrule_value;
# new ezeditorialworkflow_markings
# new ezeditorialworkflow_transitions
# new ezeditorialworkflow_workflows
drop table ezenumobjectvalue;
drop table ezenumvalue;
drop table ezfind_elevate_configuration;
drop table ezforgot_password;
# new ezform_field_attributes
# new ezform_field_validators
# new ezform_fields
# new ezform_form_submission_data
# new ezform_form_submissions
# new ezform_forms
drop table ezgeneral_digest_user_settings;
# keep ezgmaplocation
# keep ezimagefile
drop table ezinfocollection;
drop table ezinfocollection_attribute;
drop table ezisbn_group;
drop table ezisbn_group_range;
drop table ezisbn_registrant_range;
# keep ezkeyword
# keep ezkeyword_attribute_link
drop table ezm_block;
drop table ezm_pool;
# keep ezmedia
drop table ezmessage;
drop table ezmodule_run;
drop table ezmultipricedata;
# keep eznode_assignment
# keep eznotification;
drop table eznotificationcollection;
drop table eznotificationcollection_item;
drop table eznotificationevent;
drop table ezoperation_memento;
drop table ezorder;
drop table ezorder_item;
drop table ezorder_nr_incr;
drop table ezorder_status;
drop table ezorder_status_history;
# keep ezpackage;
# new ezpage_attributes
# new ezpage_blocks
# new ezpage_blocks_design
# new ezpage_blocks_visibility
# new ezpage_map_attributes_blocks
# new ezpage_map_blocks_zones
# new ezpage_map_zones_pages
# new ezpage_pages
# new ezpage_zones
# new ezpaymentobject
drop table ezpdf_export;
drop table ezpending_actions;
# keep ezpolicy
# keep ezpolicy_limitation
# keep ezpolicy_limitation_value
# keep ezpreferences
drop table ezprest_authcode;
drop table ezprest_authorized_clients;
drop table ezprest_clients;
drop table ezprest_token;
# new ezproductcategory
# new ezproductcollection
# new ezproductcollection_item
# new ezproductcollection_item_opt
drop table ezpublishingqueueprocesses;
# keep ezrole
drop table ezrss_export;
drop table ezrss_export_item;
drop table ezrss_import;
drop table ezscheduled_script;
# keep ezsearch_object_word_link
drop table ezsearch_search_phrase;
# keep ezsearch_word
# keep ezsection
# keep ezsession
drop table ezsi_files;
# new ezsite
# new ezsite_data
# new ezsite_public_access
drop table ezstarrating;
drop table ezstarrating_data;
drop table ezsubtree_notification_rule;
drop table ezsurvey;
drop table ezsurveymetadata;
drop table ezsurveyquestion;
drop table ezsurveyquestionmetadata;
drop table ezsurveyquestionresult;
drop table ezsurveyrelatedconfig;
drop table ezsurveyresult;
# keep eztags
# keep eztags_attribute_link
# keep eztags_keyword
drop table eztipafriend_counter;
drop table eztipafriend_request;
drop table eztrigger;
# keep ezurl
# keep ezurl_object_link
# keep ezurlalias
# keep ezurlalias_ml
# keep ezurlalias_ml_incr
# keep ezurlwildcard
# keep ezuser
# keep ezuser_accountkey
drop table ezuser_discountrule;
# keep ezuser_role
# keep ezuser_setting
drop table ezuservisit;
drop table ezvatrule;
drop table ezvatrule_product_category;
drop table ezvattype;
drop table ezview_counter;
drop table ezwaituntildatevalue;
drop table ezwishlist;
drop table ezworkflow;
drop table ezworkflow_assign;
drop table ezworkflow_event;
drop table ezworkflow_group;
drop table ezworkflow_group_link;
drop table ezworkflow_process;
drop table ezx_approve2_event;
drop table ezx_approve_status;
drop table ezx_approve_status_user_link;
drop table ezx_ezpnet_branch;
drop table ezx_ezpnet_installation;
drop table ezx_ezpnet_large_store;
drop table ezx_ezpnet_mod_patch_item;
drop table ezx_ezpnet_module_branch;
drop table ezx_ezpnet_module_inst;
drop table ezx_ezpnet_module_patch;
drop table ezx_ezpnet_mon_group;
drop table ezx_ezpnet_mon_item;
drop table ezx_ezpnet_mon_result;
drop table ezx_ezpnet_mon_value;
drop table ezx_ezpnet_patch;
drop table ezx_ezpnet_patch_item;
drop table ezx_ezpnet_patch_sql_st;
drop table ezx_ezpnet_soap_log;
drop table ezx_ezpnet_storage;
drop table ezx_oauth_client_consumer_user;
drop table ezx_mbpaex;
drop table financial_transactions;
# new ibexa_attribute_definition
# new ibexa_attribute_definition_assignment
# new ibexa_attribute_definition_ml
# new ibexa_attribute_group
# new ibexa_attribute_group_ml
# new ibexa_cart
# new ibexa_cart_entry
# new ibexa_cart_entry_ml
# new ibexa_catalog
# new ibexa_catalog_ml
# new ibexa_content_customer_group
# new ibexa_corporate_application_state
# new ibexa_corporate_company_history
# new ibexa_corporate_member_assignment
# new ibexa_currency
# new ibexa_customer_group
# new ibexa_customer_group_ml
# new ibexa_measurement_range_value
# new ibexa_measurement_type
# new ibexa_measurement_unit
# new ibexa_measurement_value
# new ibexa_migrations
# new ibexa_migrations_lock
# new ibexa_product_specification
# new ibexa_product_specification_asset
# new ibexa_product_specification_attribute
# new ibexa_product_specification_attribute_boolean
# new ibexa_product_specification_attribute_float
# new ibexa_product_specification_attribute_integer
# new ibexa_product_specification_attribute_measurement_range
# new ibexa_product_specification_attribute_measurement_value
# new ibexa_product_specification_attribute_selection
# new ibexa_product_specification_attribute_simple_custom
# new ibexa_product_specification_availability
# new ibexa_product_specification_price
# new ibexa_product_specification_price_customer_group
# new ibexa_product_type_specification_region_vat_category
# new ibexa_segment_group_map
# new ibexa_segment_groups
# new ibexa_segment_user_map
# new ibexa_segments
# new ibexa_setting
# new ibexa_taxonomy_assignments
# new ibexa_taxonomy_entries
# new ibexa_token
# new ibexa_token_type
# new ibexa_user_invitations
# new ibexa_user_invitations_assignments
# new ibexa_workflow_version_lock
# new jms_cron_jobs
# new jms_job_dependencies
# new jms_job_related_entities
# new jms_job_statistics
# new jms_jobs
